# Base path for output data
TMP_DATA_BASE_OUTPUT_PATH = "./output/data"

# Command line args default values
RATE_LIMITER_MAX_RETRIES_DEFAULT = 3
EXCHANGES_WITH_SIMILAR_TRADES_TO_ANALYZE_DEFAULT= 1
EXCHANGES_TO_ANALYZE_DEFAULT_LIMIT = 1
WRITE_TO_S3_DEFAULT = True

# Analyzer constants
HISTORICAL_DATA_LOOKBACK_DAYS_DEFAULT = 30
HISTORICAL_VOLUME_DATE_FORMAT = '%Y-%m-%d'

# Logging constants
LOGGING_DEFAULT_LEVEL = "info"

# AWS Required Env vars
AWS_REQUIRED_CONFIGS = ["S3_ENDPOINT", "AWS_BUCKET", "AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_REGION"]

# Rate Limiter Constants
RATE_LIMITER_DEFAULT_WAIT_TIME_SECONDS = 1